# Generated by Django 4.2 on 2024-02-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_accessuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessuser',
            name='access',
            field=models.BooleanField(default=True, verbose_name='Разрешить/запретить \nдоступ к продукту'),
        ),
    ]
