# Generated by Django 4.2 on 2024-03-01 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_accessuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessuser',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт'),
            preserve_default=False,
        ),
    ]
