# Generated by Django 4.2 on 2024-03-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_accessuser_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='start_datetime',
            field=models.DateTimeField(verbose_name='Дата и время старта продукта'),
        ),
    ]
